apiVersion: v1
kind: Secret
metadata:
  name: glasslab-agent-secrets
  namespace: glasslab-agents
type: Opaque
stringData:
  VLLM_API_KEY: cdfa7873ceacb8bbcc2248dc5c3bb34f447ee6f46cb57d19
  GLASSLAB_AGENT_QWEN_API_KEY: cdfa7873ceacb8bbcc2248dc5c3bb34f447ee6f46cb57d19
  HUGGING_FACE_HUB_TOKEN: ""
