all:
  vars:
    ansible_python_interpreter: /usr/bin/python3
  children:
    provisioner:
      hosts:
        glasslab-pxe-01:
          ansible_connection: local
          ansible_host: 192.168.1.44
          ansible_user: glasslab
          node_ip: 192.168.1.44
          infra_role: provisioner
    control_plane:
      hosts:
        cp01:
          ansible_host: 192.168.1.49
          ansible_user: clusteradmin
          ansible_ssh_private_key_file: /home/glasslab/.ssh/id_ed25519
          node_ip: 192.168.1.49
          node_mac: 18:66:da:23:44:38
    workers:
      hosts:
        node01:
          ansible_host: 192.168.1.48
          ansible_user: clusteradmin
          ansible_ssh_private_key_file: /home/glasslab/.ssh/id_ed25519
          node_ip: 192.168.1.48
          node_mac: 90:b1:1c:90:22:50
        node02:
          ansible_host: 192.168.1.11
          ansible_user: clusteradmin
          ansible_ssh_private_key_file: /home/glasslab/.ssh/id_ed25519
          node_ip: 192.168.1.11
          node_mac: 90:b1:1c:90:ad:18
    k8s_nodes:
      children:
        control_plane: {}
        workers: {}
