apiVersion: v1
kind: Service
metadata:
  name: glasslab-schedule-worker
  namespace: glasslab-v2
spec:
  type: ClusterIP
  selector:
    app.kubernetes.io/name: glasslab-schedule-worker
  ports:
    - name: http
      port: 8094
      targetPort: http
