apiVersion: v1
kind: Pod
metadata:
  name: debug-nfs
  namespace: glasslab-v2
spec:
  containers:
    - name: debug
      image: ubuntu:22.04
      command: ["sleep", "86400"]
      volumeMounts:
        - name: artifacts
          mountPath: /mnt/artifacts
  restartPolicy: Never
  nodeSelector:
    glasslab.io/gpu-vendor: nvidia
  volumes:
    - name: artifacts
      persistentVolumeClaim:
        claimName: glasslab-shared-artifacts
