apiVersion: v1
kind: Secret
metadata:
  name: glasslab-v2-workflow-api
  namespace: glasslab-v2
type: Opaque
stringData:
  GLASSLAB_WORKFLOW_API_STORE_POSTGRES_DSN: postgresql://glasslab:change-me-before-deploy@glasslab-postgres.glasslab-v2.svc.cluster.local:5432/glasslab
